Repository kiddo-capstone/kiddo-frontend, pull requests merged in 2021-02, with the labels that each got.

#20 Setup PWA & Dependencies
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/index.js
  src/logo.svg
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: deliverable 🎁, front-end 🍱

#24 Buildout context reducer
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/index.css
  src/index.js
  src/logo.svg
  src/modules/App/App.css
  src/modules/App/App.js
  src/modules/App/App.test.js
  src/modules/App/AppContext.js
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/common/header/Header.jsx
  src/modules/common/sidebar/Sidebar.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/actions.js
  src/setup/reportWebVitals.js
  src/setup/service-worker.js
  src/setup/serviceWorkerRegistration.js
  src/setupTests.js
  src/ui/button/Button.jsx
  src/ui/card/Card.jsx
  src/ui/common/colors.js
  src/ui/common/fonts.js
  src/ui/common/gradients.js
  src/ui/common/shadows.js
  src/ui/input/File.js
  src/ui/input/TextArea.jsx
  src/ui/input/index.js
  src/ui/typography/H1.js
  src/ui/typography/H2.js
  src/ui/typography/H3.js
  src/ui/typography/H4.js
  src/ui/typography/H5.js
  src/ui/typography/H6.js
  src/ui/typography/index.js
Labels: deliverable 🎁, front-end 🍱

#26 Style theme
  package-lock.json
  src/modules/App/App.js
  src/modules/common/appReducer.js
  src/modules/views/MissionControl.jsx
  src/modules/views/StyleSample.jsx
  src/ui/button/Button.js
  src/ui/button/Button.jsx
  src/ui/common/colors.js
  src/ui/common/theme.js
Labels: front-end 🍱, styling/UI 🎨

#27 Routes/views
  src/modules/App/App.js
  src/modules/common/sidebar/Sidebar.jsx
  src/modules/views/DailyMission.jsx
Labels: enhancement 🌟, front-end 🍱

#28 UI components and modules
  src/index.css
  src/modules/App/App.css
  src/modules/App/App.js
  src/modules/common/header/Header.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/StyleSample.jsx
  src/ui/containers/PageContainer.js
  src/ui/containers/TitleContainer.js
Labels: deliverable 🎁, front-end 🍱, styling/UI 🎨

#32 Error handling
  package-lock.json
  package.json
  src/modules/App/App.js
  src/modules/common/error/Error400.jsx
  src/modules/common/error/Error500.jsx
Labels: enhancement 🌟, error handling ❊, front-end 🍱

#36 AppContainer and PageContainer
  src/index.css
  src/index.js
  src/modules/App/App.js
  src/modules/common/header/Header.jsx
  src/modules/common/sidebar/Sidebar.jsx
  src/modules/views/AgentDetails.jsx
  src/ui/containers/AppContainer.js
  src/ui/containers/PageContainer.js
  src/ui/containers/TitleContainer.js
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨

#38 Connect api
  package-lock.json
  package.json
  src/modules/App/App.js
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/common/error/Error500.jsx
  src/modules/views/actions.js
Labels: enhancement 🌟, error handling ❊, front-end 🍱

#39 Build missions
  src/assets/art.js
  src/assets/explore.js
  src/assets/heart.js
  src/assets/index.js
  src/assets/kidbrain.js
  src/assets/math.js
  src/modules/common/convertDate.js
  src/modules/mission/Mission.jsx
  src/modules/views/AgentDetails.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/ui/badges/BadgeBg.js
  src/ui/button/RoundButton.js
  src/ui/common/colors.js
  src/ui/containers/BadgeContainer.js
  src/ui/containers/MediumContainer.js
  src/ui/containers/PageContainer.js
  src/ui/containers/SmallContainer.js
  src/ui/containers/index.js
Labels: deliverable 🎁, enhancement 🌟, front-end 🍱, user story 📚

#40 Auth0
  package-lock.json
  package.json
  src/index.js
  src/modules/App/App.js
  src/modules/auth/Auth.js
  src/modules/common/apiCalls.js
  src/ui/containers/AppContainer.js
Labels: deliverable 🎁, front-end 🍱, user story 📚

#42 Feature agent details
  src/assets/heart.js
  src/modules/common/convertDate 2.js
  src/modules/views/AgentDetails.jsx
  src/ui/button/RoundButton 2.js
  src/ui/common/colors.js
  src/ui/common/theme.js
  src/ui/containers/AppContainer.js
  src/ui/containers/PageContainer.js
  src/ui/progressBar/progressBar.js
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨, user story 📚

#43 Single mission view
  src/cannedData.js
  src/modules/App/App.js
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/mission/Mission.jsx
  src/modules/task/Task.js
  src/modules/views/DailyMission.jsx
  src/modules/views/TaskView.jsx
  src/ui/containers/TitleContainer.js
Labels: deliverable 🎁, front-end 🍱, user story 📚

#44 Task view
  src/assets/art.js
  src/modules/auth/Auth.js
  src/modules/common/appReducer.js
  src/modules/mission/Mission.jsx
  src/modules/task/Task.js
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/TaskView.jsx
  src/ui/badges/BadgeBg.js
  src/ui/button/Button.js
  src/ui/button/RoundButton.js
  src/ui/common/colors.js
  src/ui/containers/BadgeContainer.js
  src/ui/containers/PageContainer.js
  src/ui/containers/TitleContainer.js
  src/ui/decorative/AccentLine.js
Labels: deliverable 🎁, enhancement 🌟, front-end 🍱

#46 Feature image upload
  src/modules/common/apiCalls.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/StyleSample.jsx
  src/ui/containers/ImageCapture.js
  src/ui/modal/Modal.js
  src/ui/modal/ModalWrapper.js
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨, user story 📚

#45 Task view
  src/modules/mission/Mission.jsx
  src/modules/tasks/Journal.js
  src/modules/views/MissionControl.jsx
  src/modules/views/TaskView.jsx
  src/ui/button/Button.js
  src/ui/containers/TitleContainer.js
Labels: deliverable 🎁, front-end 🍱, styling/UI 🎨, user story 📚

#47 Assets
  package-lock.json
  src/assets/accomplishment.png
  src/assets/activity.png
  src/assets/camera.png
  src/assets/creativity.png
  src/assets/error-404.png
  src/assets/intelligence.png
  src/assets/kids.js
  src/assets/kids_trio.png
  src/assets/magnifying-glass.png
  src/assets/servers-down.png
  src/assets/user.png
  src/modules/auth/Auth.js
  src/modules/common/convertDate 2.js
  src/modules/common/error/Error400.jsx
  src/modules/common/error/Error500.jsx
  src/modules/mission/Mission.jsx
  src/modules/mission/MissionComplete.jsx
  src/modules/views/AgentDetails.jsx
  src/modules/views/MissionControl.jsx
  src/ui/button/RoundButton 2.js
  src/ui/containers/AppContainer.js
  src/ui/containers/ImageCapture.js
  src/ui/containers/MediumContainer.js
Labels: front-end 🍱

#49 Photo evidence
  src/cannedData.js
  src/modules/task/Task.js
  src/modules/tasks/ImageCapture.js
  src/modules/tasks/Journal.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/StyleSample.jsx
  src/modules/views/TaskView.jsx
  src/ui/button/RoundButton.js
  src/ui/modal/Modal.js
  src/ui/modal/ModalWrapper.js
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨, user story 📚

#53 Task completion logic (state/DB synching)
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/common/error/Error400.jsx
  src/modules/tasks/ImageCapture.js
  src/modules/tasks/Journal.js
  src/modules/views/DailyMission.jsx
  src/modules/views/TaskView.jsx
Labels: deliverable 🎁, documentation, front-end 🍱, styling/UI 🎨
