Repository kiddo-capstone/kiddo-frontend, pull requests merged in 2021-03, with the labels that each got.

#58 Style completed states
  src/cannedData.js
  src/index.css
  src/modules/task/Task.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/DailyMission.jsx
Labels: deliverable 🎁, front-end 🍱, styling/UI 🎨, user story 📚

#59 Bug fixes and adjustments
  src/modules/common/convertDate.js
  src/modules/tasks/Journal.js
  src/modules/views/DailyMission.jsx
  src/modules/views/TaskView.jsx
Labels: front-end 🍱, styling/UI 🎨

#62 Message modal
  src/modules/tasks/ImageCapture.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/StyleSample.jsx
  src/ui/modal/ModalMessage.js
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨

#63 Select KidDo User
  src/modules/App/App.js
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/common/error/Error400.jsx
  src/modules/login/Login.js
  src/modules/task/Task.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/TaskView.jsx
Labels: front-end 🍱

#64 Tdd
  .travis.yml
  cypress.json
  cypress/fixtures/mission.json
  cypress/fixtures/missionTask.json
  cypress/fixtures/missionTasks.json
  cypress/fixtures/missions.json
  cypress/fixtures/task.json
  cypress/fixtures/tasks.json
  cypress/fixtures/user.json
  cypress/integration/App.spec.js
  cypress/integration/Missions.spec.js
  cypress/integration/Sidebar.spec.js
  cypress/plugins/index.js
  cypress/screenshots/App.spec.js/App -- should render mission control (failed).png
  cypress/screenshots/Missions.spec.js/MissionControl -- should display information on a mission card (failed).png
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/App.spec.js.mp4
  cypress/videos/Missions.spec.js.mp4
  package-lock.json
  package.json
  src/index.js
  src/modules/login/Login.js
  src/modules/mission/Mission.jsx
  src/modules/tasks/Journal.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/StatusForm.jsx
  src/modules/views/StyleSample.jsx
  src/modules/views/TaskView.jsx
  src/test/App.test.js
  src/test/MissionControl.test.js
  src/test/testData.js
Labels: front-end 🍱, testing 🧪

#65 Mission Cards: Contextual points and task category badges
  src/modules/mission/Mission.jsx
  src/modules/task/Task.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/StatusForm.jsx
  src/ui/button/RoundButton.js
Labels: front-end 🍱

#66 Agent points
  src/modules/common/apiCalls.js
  src/modules/login/Login.js
  src/modules/login/SignUp.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/Welcome.jsx
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨

#67 TaskView resources and small fixes
  package-lock.json
  package.json
  src/modules/task/Task.js
  src/modules/tasks/Journal.js
  src/modules/views/DailyMission.jsx
  src/modules/views/TaskView.jsx
  src/ui/modal/ModalMessage.js
Labels: deliverable 🎁, front-end 🍱

#68 Welcome
  package-lock.json
  src/assets/art.js
  src/assets/bubbles.svg
  src/assets/explore.js
  src/assets/heart.js
  src/assets/index.js
  src/assets/kidbrain.js
  src/assets/kids.js
  src/assets/math.js
  src/assets/user.png
  src/modules/common/apiCalls.js
  src/modules/login/LoginForm.js
  src/modules/login/SignUp.js
  src/modules/login/UserIndex.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/StatusForm.jsx
  src/modules/views/TaskView.jsx
  src/modules/views/Welcome.jsx
  src/test/App.test.js
  src/ui/common/gradients.js
  src/ui/common/theme.js
  src/ui/containers/AppContainer.js
  src/ui/typography/H1.js
  src/ui/typography/H2.js
  src/ui/typography/H3.js
  src/ui/typography/H4.js
  src/ui/typography/H5.js
  src/ui/typography/H6.js
  src/ui/typography/index.js
Labels: enhancement 🌟, front-end 🍱

#69 Add back buttons
  src/assets/backarrow.js
  src/modules/login/LoginForm.js
  src/modules/login/UserIndex.js
  src/modules/mission/Mission.jsx
  src/modules/views/AgentDetails.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/TaskView.jsx
  src/ui/badges/BadgeBg.js
  src/ui/containers/AppContainer.js
Labels: front-end 🍱, styling/UI 🎨

#71 Parent View
  src/modules/App/App.js
  src/modules/auth/MiniAuth.js
  src/modules/mission/ExampleMission.jsx
  src/modules/parents/TransferList.js
  src/modules/parents/parentApiCalls.js
  src/modules/tasks/ImageCapture.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/ParentView.jsx
  src/modules/views/StatusForm.jsx
  src/modules/views/TaskView.jsx
Labels: front-end 🍱

#70 User points display and README
  README.md
  src/modules/common/apiCalls.js
  src/modules/login/Login.js
  src/modules/login/LoginForm.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/StyleSample.jsx
  src/ui/containers/AppContainer.js
  src/ui/containers/PageContainer.js
Labels: enhancement 🌟, front-end 🍱, user story 📚

#72 Small styles branch
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/modules/login/Login.js
  src/modules/views/Welcome.jsx
  src/ui/button/Button.js
  src/ui/card/Card.jsx
  src/ui/input/TextArea.jsx
  src/ui/modal/ModalWrapper.js
Labels: enhancement 🌟, front-end 🍱

#74 Fix side drawer
  cypress.json
  cypress/integration/App.spec.js
  cypress/integration/Missions.spec.js
  cypress/integration/Sidebar.spec.js
  cypress/screenshots/App.spec.js/App -- should render 404 page (failed).png
  cypress/screenshots/App.spec.js/App -- should render mission control (failed).png
  cypress/screenshots/App.spec.js/App -- should render sidebar (failed).png
  cypress/screenshots/Missions.spec.js/MissionControl -- should display information on a mission card (failed).png
  cypress/screenshots/Sidebar.spec.js/Sidebar -- should allow the user to update their status (failed).png
  cypress/screenshots/Sidebar.spec.js/Sidebar -- should display stats (failed).png
  cypress/videos/App.spec.js.mp4
  cypress/videos/Missions.spec.js.mp4
  cypress/videos/Sidebar.spec.js.mp4
  src/modules/views/DailyMission.jsx
  src/modules/views/TaskView.jsx
  src/test/App.test.js
  src/ui/containers/AppContainer.js
Labels: bug, front-end 🍱, styling/UI 🎨

#77 daily mission view bug
  src/modules/App/App.js
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
Labels: bug

#81 Update: Parent/Child Accounts and Implementation, Bug fixes
  src/modules/auth/MiniAuth.js
  src/modules/common/apiCalls.js
  src/modules/parents/parentApiCalls.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/ParentView.jsx
Labels: bug, enhancement 🌟, front-end 🍱

#83 User stats animations
  src/assets/gold_coin.png
  src/assets/index.js
  src/modules/common/apiCalls.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/AgentStats.jsx
  src/ui/animations/SpinningCoin.js
  src/ui/animations/goldCoinRain.js
  src/ui/dataVisuals/ProgressBar.js
Labels: enhancement 🌟, front-end 🍱, styling/UI 🎨

#82 Fix/tests ci
  .travis.yml
  cypress/integration/Missions.spec.js
  cypress/screenshots/App.spec.js/App -- should render 404 page (failed).png
  cypress/screenshots/App.spec.js/App -- should render sidebar (failed).png
  cypress/screenshots/Missions.spec.js/MissionControl -- should display information on a mission card (failed).png
  cypress/screenshots/Sidebar.spec.js/Sidebar -- should allow the user to update their status (failed).png
  cypress/screenshots/Sidebar.spec.js/Sidebar -- should display stats (failed).png
  cypress/videos/App.spec.js.mp4
  cypress/videos/Missions.spec.js.mp4
  cypress/videos/Sidebar.spec.js.mp4
  src/modules/App/App.js
Labels: bug, front-end 🍱

#84 Tie together new parent/user relationship, persist on refresh
  .travis.yml
  cypress/integration/App.spec.js
  cypress/integration/Sidebar.spec.js
  cypress/screenshots/App.spec.js/App -- should render mission control (failed).png
  cypress/screenshots/Sidebar.spec.js/Sidebar -- should allow the user to update their status (failed).png
  cypress/videos/App.spec.js.mp4
  cypress/videos/Sidebar.spec.js.mp4
  src/index.js
  src/modules/App/App.js
  src/modules/auth/MiniAuth.js
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/views/AccountsView.jsx
  src/modules/views/AgentDetails.jsx
  src/modules/views/AgentStats.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/ParentView.jsx
  src/test/MissionControl.test.js
  src/ui/card/Card.js
  src/ui/containers/PageContainer.js
Labels: MVP++, bug, enhancement 🌟, front-end 🍱

#86 Sidebar ux
  src/index.js
  src/modules/task/Task.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/AgentStats.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/TaskView.jsx
  src/ui/containers/AppContainer.js
  src/ui/containers/PageContainer.js
Labels: bug, front-end 🍱, styling/UI 🎨

#89 Bux fixes: accounts view, styling, landing page
  src/index.css
  src/modules/App/App.js
  src/modules/auth/Auth.js
  src/modules/auth/MiniAuth.js
  src/modules/views/AgentDetails.jsx
  src/ui/containers/AppContainer.js
Labels: bug

#92 Bug Hunt
  src/modules/App/App.js
  src/modules/auth/MiniAuth.js
  src/modules/tasks/Journal.js
  src/modules/views/AccountsView.jsx
  src/modules/views/AgentDetails.jsx
  src/ui/animations/goldCoinRain.js
  src/ui/card/Card.js
Labels: bug, front-end 🍱

#94 Parent rewards
  src/modules/common/apiCalls.js
  src/modules/parents/ChildList.js
  src/modules/parents/NewChildForm.js
  src/modules/parents/RewardForm.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/ParentView.jsx
Labels: MVP++, enhancement 🌟, front-end 🍱

#96 Refactor and bug fixes
  src/modules/App/App.js
  src/modules/auth/MiniAuth.js
  src/modules/common/appReducer.js
  src/modules/login/Login.js
  src/modules/login/LoginForm.js
  src/modules/login/SignUp.js
  src/modules/parents/ChildList.js
  src/modules/parents/NewChildForm.js
  src/modules/parents/RewardForm.js
  src/modules/views/AccountsView.jsx
  src/modules/views/AgentStats.jsx
  src/modules/views/DailyMission.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/ParentView.jsx
  src/ui/card/Card.js
Labels: bug

#97 Custom tasks
  package-lock.json
  src/modules/App/App.js
  src/modules/common/apiCalls.js
  src/modules/parents/TaskCreation.js
  src/modules/parents/TransferList.js
  src/modules/parents/parentApiCalls.js
  src/modules/rewards/RewardCard.jsx
  src/modules/views/MissionControl.jsx
  src/modules/views/ParentView.jsx
  src/modules/views/RewardStore.jsx
  src/ui/containers/AppContainer.js
  src/ui/containers/PageContainer.js
  src/ui/modal/ModalWrapper.js
Labels: MVP++, enhancement 🌟, front-end 🍱

#98 Loading anim
  src/modules/common/LoadingAnimation.js
  src/modules/views/AccountsView.jsx
  src/modules/views/MissionControl.jsx
Labels: enhancement 🌟, front-end 🍱

#100 Styles/reward store
  src/modules/App/App.js
  src/modules/parents/TaskCreation.js
  src/modules/rewards/RewardCard.jsx
  src/modules/views/AgentDetails.jsx
  src/modules/views/RewardStore.jsx
  src/ui/animations/SpinningCoin.js
  src/ui/containers/AppContainer.js
  src/ui/dataVisuals/ProgressBar.js
Labels: enhancement 🌟, front-end 🍱

#101 Bugs
  src/modules/common/apiCalls.js
  src/modules/common/appReducer.js
  src/modules/rewards/RewardCard.jsx
  src/modules/views/RewardStore.jsx
  src/ui/containers/PageContainer.js
Labels: bug, front-end 🍱

#102 Accessibility/parent child views
  src/modules/common/appReducer.js
  src/modules/parents/ChildList.js
  src/modules/parents/NewChildForm.js
  src/modules/parents/RewardForm.js
  src/modules/parents/TransferList.js
  src/modules/rewards/RewardCard.jsx
  src/modules/task/Task.js
  src/modules/views/AgentDetails.jsx
  src/modules/views/AgentStats.jsx
  src/modules/views/ParentView.jsx
  src/modules/views/RewardStore.jsx
  src/modules/views/Welcome.jsx
Labels: accessibility, front-end 🍱
